config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    request.env['warden'].user(:admin).present?
  end
end

Rails.application.routes.default_url_options[:host] =
  Rails.env.production? ? 'http://chick-chuck.com' : 'localhost:3000'
Rails.application.routes.draw do
  # WWW redirect
  match '(*any)',
        to: redirect(subdomain: ''),
        via: :all,
        constraints: { subdomain: 'www' }
  # 404 old pages to remove!
  get '/he', to: redirect('/404')
  get '/he/*other', to: redirect('/404')
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    # 404
    get '404', to: 'errors#page_not_found'
    # 404 old pages to remove!
    # get "/contents/*other", to: redirect('/404')
    # get "/news/*other", to: redirect('/404')
    # get "/trucks/*other", to: redirect('/404')
    # Root path
    root to: 'main#index'
    # Sitemap
    get 'sitemap.xml', to: 'main#sitemap', format: 'xml', as: :sitemap
    # Robots
    get 'robots.txt',  to: 'main#robots',  format: 'txt', as: :robots
    # Favicon
    get 'favicon.png', to: 'main#favicon', format: 'png', as: :favicon
    # Cookies
    get 'cookies', to: 'main#cookies', as: :cookies, defaults: { format: 'turbo_stream' }

    # --- Content ---

    # Users
    resources :users, only: %i[index show], controller: 'users/users', path: 'carriers' do
      get '/modal',         to: 'users/users#modal',                  as: 'modal'
      get '/contacts',      to: 'users/users#contacts',               as: 'contacts'
    end

    # Products
    resources :products, only: %i[index show], controller: 'contents/products'
    get 'seller/:user_id', to: 'contents/products#user_products', as: 'user_products'

    # Calculator
    resource :calculator, only: %i[show], controller: 'contents/calculators' do
      get '/company/:company_id/calculator', to: 'contents/calculators#company_calculator', as: 'company'
    end

    # Moving preparation
    get '/moving_preparation', to: 'contents/moving_preparation#index', as: 'moving_preparation'

    # Comments
    resources :comments, only: %i[new edit create update destroy], controller: 'feedbacks/comments' do
      resources :comments, only: %i[new edit create update destroy], controller: 'feedbacks/comments'
    end

    # About service
    get 'about', to: 'contents/about#index', as: 'about'

    # Feedbacks
    resources :feedbacks, only: %i[index create edit update], controller: 'contents/feedbacks'

    # News content
    # resources :news, only: %i[show index], controller: 'contents/news' do
    #   resources :comments, only: %i[new edit create update destroy], controller: 'feedbacks/comments'
    # end

    # --- End of content ---

    # Admins
    devise_for :admins, controllers: { registrations: 'admins/registrations' }, skip: %i[registrations confirmations]
    as :admin do
      get 'admins/edit',  to: 'admins/registrations#edit',    as: 'edit_admin_registration'
      put 'admins',       to: 'admins/registrations#update',  as: 'admin_registration'
      namespace :admins, constraints: AdminConstraint.new do
        # Analytics
        mount ActiveAnalytics::Engine => '/analytics'
        # Sidekiq
        mount Sidekiq::Web => '/sidekiq'
        resources :categories, except: %i[show], controller: 'catalog/categories' do
          resources :things, except: %i[show], controller: 'catalog/things'
        end
        resources :news, except: %i[show]
        resources :languages, except: %i[index show]
        resources :districts, except: %i[show] do
          resources :cities
        end
        resource :dashboard, only: :show do
          get :users
        end
        post '/publish/news/:id', to: 'news#publish', as: 'publish_news'
      end
    end

    # Companies
    devise_for :companies, controllers: { registrations: 'companies/registrations' }
    namespace :companies do
      resources :prices,     only: %i[index create update]
      resource  :calculator, only: %i[create update]
      resource  :gallery,    only: %i[show create]
      get  '/dashboard',                to: 'dashboard#index',              as: 'dashboard'
      get  '/profile',                  to: 'profiles#profile',             as: 'edit_profile'
      put  '/profile',                  to: 'profiles#profile_update',      as: 'profile'
      get  '/company_info',             to: 'profiles#company_info',        as: 'edit_company_info'
      put  '/company_info',             to: 'profiles#company_info_update', as: 'company_info'
    end

    # Clients
    devise_for :clients, controllers: { registrations: 'clients/registrations' }, skip: :omniauth_callbacks
    namespace :clients do
      resource :profile, only: %i[edit update]
      get '/dashboard', to: 'dashboard#index', as: 'dashboard'
    end

    # Users
    namespace :users do
      resources :favorites, only: %i[index create destroy]
      resources :products, except: %i[show] do
        post '/publish',      to: 'products#publish',             as: 'publish'
        post '/mark_as_sold', to: 'products#mark_as_sold',        as: 'mark_as_sold'
      end
      # Email subscribers
      resources :mailers, only: [:create]
    end

    # Reviews
    resources :reviews, only: %i[new create edit update], controller: 'feedbacks/reviews'

    # Carrierwave attachments
    namespace :carrierwave do
      resources :images, only: %i[show destroy]
    end

    # Rooms
    resources :rooms, only: %i[index show create], param: :title, controller: 'feedbacks/rooms' do
      resources :messages, only: %i[edit update create destroy], controller: 'feedbacks/messages'
    end

    # Notifications
    resources :notifications, only: [:index], controller: 'feedbacks/notifications'
  end

  # Devise with omniauth_callbacks
  devise_for :clients, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'clients/omniauth_callbacks' }
end

app/models/client.rb
# frozen_string_literal: true

class Client < User
  include ClientDecorate
  devise :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  has_many :products, class_name: 'Product', dependent: :destroy, foreign_key: :user_id

  def self.from_omniauth(auth)
    name_split = auth.info.name.split(' ')

    user = Client.where(email: auth.info.email).first
    user ||= Client.create!(
      provider: auth.provider, uid: auth.uid, email: auth.info.email, password: Devise.friendly_token[0, 20], confirmed_at: Time.now,
      first_name: name_split.first, last_name: name_split.last
    )

    # if user.remote_avatar_url != auth.info.image
    #       require 'open-uri'
    #
    #       user.remote_avatar_url = auth.info.image
    #       user.save
    #     end
    user
  end

  def company_review(company)
    Review.find_by(user_id: self, reviewable_id: company)
  end

  # Mailer
  def after_confirmation
    Subscriber.create(email:) unless Subscriber.where(email:).present?
  end
end

app/controllers/clients/dashboard_controller.rb
# frozen_string_literal: true

module Clients
  class DashboardController < ApplicationController
    layout 'profile_layout'
    before_action :authenticate_client!
    before_action :set_client, only: %i[index]

    def index; end

    private

    def set_client
      @client = current_client
    end
  end
end

app/controllers/clients/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Clients
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
      @user = Client.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
      else
        session['devise.facebook_data'] = request.env['omniauth.auth'].except(:extra)
        redirect_to new_client_registration_url
      end
    end

    def failure
      redirect_to root_path
    end

    def google_oauth2
      @user = Client.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:notice, :success, kind: 'Google') if is_navigational_format?
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except('extra')
        redirect_to new_client_registration_url, alert: @user.errors.full_messages.join("\n")
      end
    end
  end
end

app/controllers/clients/products_controller.rb
# frozen_string_literal: true

module Clients
  class ProductsController < ApplicationController
    include Feedbacks::ReviewsHelper
    layout 'profile_layout'
    before_action :authenticate_client!
    before_action :set_product, only: %i[edit update publish mark_as_sold destroy]
    before_action :filter_product, only: %i[new create edit update]

    def index
      @pagy, @products = pagy(current_client.products.newest, items: 8, fragment: '#products')
      @products = @products.decorate
    end

    def new
      @product = current_client.products.new.decorate
    end

    def create
      @product = current_client.products.build(product_params).decorate

      respond_to do |format|
        if @product.save
          format.html do
            redirect_to clients_products_path,
                        success: t('flash.success.created', model: "#{@product.model_name.human} #{@product.title}")
          end
        else
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    def edit; end

    def update
      respond_to do |format|
        if @product.update(product_params)
          format.turbo_stream do
            flash.now[:success] = t('flash.success.updated', model: "#{@product.model_name.human} #{@product.title}")
          end
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    def publish
      return unless current_client.products.include?(@product)

      respond_to do |format|
        if @product.published == false
          if @product.update(published: true)
            format.turbo_stream do
              flash.now[:success] =
                t('flash.success.published', model: "#{@product.model_name.human} #{@product.title}")
            end
          end
        elsif @product.update(published: false)
          format.turbo_stream do
            flash.now[:success] = t('flash.success.hided', model: "#{@product.model_name.human} #{@product.title}")
          end
        end
      end
    end

    def mark_as_sold
      return unless current_client.products.include?(@product)

      respond_to do |format|
        if @product.sold == false
          @product.update(sold: true, published: false)
          format.turbo_stream do
            flash.now[:success] = t('flash.success.hided', model: "#{@product.model_name.human} #{@product.title}")
          end
        else
          @product.update(sold: false, published: true)
          format.turbo_stream do
            flash.now[:success] =
              t('flash.success.published', model: "#{@product.model_name.human} #{@product.title}")
          end
        end
      end
    end

    def destroy
      respond_to do |format|
        if @product.destroy
          format.turbo_stream { flash.now[:success] = t('flash.success.destroyed', model: @product.model_name.human) }
        else
          format.html { render :index, status: :unprocessable_entity }
        end
      end
    end

    private

    def product_params
      params.require(:product).permit(:category_id, :thing_id, :title, :condition, :description, :price, images: [],
                                                                                                         append_images: [])
    end

    def filter_product
      @categories = Category.all.decorate
      @things = Category.find_by(id: params[:category_id])&.things&.decorate || @product&.category&.things&.decorate || Thing.all.decorate
    end

    def set_product
      @product = Product.find_by_id(params[:id]).decorate
    end
  end
end

app/controllers/clients/profiles_controller.rb
# frozen_string_literal: true

module Clients
  class ProfilesController < ApplicationController
    layout 'profile_layout'
    before_action :authenticate_client!
    before_action :set_profile, only: %i[edit update]

    def edit; end

    def update
      I18n.locale = set_profile_params[:locale] unless set_profile_params[:locale] == @user.locale
      respond_to do |format|
        if @user.update set_profile_params
          format.html do
            redirect_to edit_clients_profile_path, success: t('flash.success.updated', model: t('flash.account'))
          end
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    private

    def set_profile
      @user = current_client
    end

    def set_profile_params
      params.require(:client).permit(:first_name, :last_name, :avatar, :gender, :birthday, :city_id, :locale,
                                     :remove_avatar, :additional_phone, :whatsapp, :telegram, :facebook)
    end
  end
end

app/controllers/clients/registrations_controller.rb
# frozen_string_literal: true

module Clients
  class RegistrationsController < Devise::RegistrationsController
    layout 'profile_layout', except: %i[new create]
    before_action :configure_sign_up_params, only: [:create], if: :devise_controller?
    before_action :configure_account_update_params, only: [:update], if: :devise_controller?

    # GET /resource/sign_up
    def new
      set_meta_tags(
        title: t('meta.client.sign_up.title'),
        description: t('meta.client.sign_up.desc'),
        noindex: true
      )
      super
      # build_resource({})
      # resource.build_profile
      # respond_with resource
    end

    # POST /resource
    # def create
    #    super
    #  end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #    super
    #  end

    # DELETE /resource
    def destroy
      super do
        # Turbo requires redirects be :see_other (303); so override Devise default (302)
        return redirect_to root_path, status: :see_other
      end
    end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the client wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    def cancel
      expire_data_after_sign_in!
      redirect_to root_path
    end

    protected

    def update_resource(resource, params)
      # Allows user to update registration information without password.
      return resource.update_without_password(params.except('current_password')) if resource.provider.present?

      super
    end

    # If you have extra params to permit, append them to the sanitizer.

    def sign_up_params
      devise_parameter_sanitizer.sanitize(:sign_up) { |client| client.permit(permitted_attributes) }
    end

    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: permitted_attributes)
    end

    def permitted_attributes
      %i[ email phone password password_confirmation locale
          first_name last_name avatar gender birthday city_id additional_phone whatsapp telegram facebook]
    end

    def configure_account_update_params
      devise_parameter_sanitizer.permit(:account_update, keys: permitted_attributes)
    end

    def after_update_path_for(_resource)
      edit_client_registration_path
    end

    def after_inactive_sign_up_path_for(_resource)
      new_confirmation_path(_resource)
    end

    # The path used after sign up.
    # def after_sign_up_path_for(_resource)
    #       flash[:success] = "You are welcome, #{current_client.first_name}!" if client_signed_in?
    #       root_path
    #     end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/clients/sessions_controller.rb
# frozen_string_literal: true

module Clients
  class SessionsController < Devise::SessionsController
    before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    def new
      set_meta_tags(
        title: t('sign_in.title'),
        noindex: true
      )
      super
    end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    def destroy
      super do
        # Turbo requires redirects be :see_other (303); so override Devise default (302)
        return redirect_to after_sign_out_path_for(resource_name), status: :see_other
      end
    end

    protected

    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_in_params
      devise_parameter_sanitizer.permit(:sign_in, keys: %i[login password])
    end

    def after_sign_in_path_for(_resource)
      flash[:success] = "You are welcome, #{current_client.first_name}!" if client_signed_in?
      root_path
    end

    def after_sign_out_path_for(_resource_or_scope)
      flash[:info] = 'See you later!'
      root_path
    end
  end
end

app/views/clients/shared/_about_client.html.erb
<!-- About user -->
<section class="mx-5 flex flex-col items-center relative space-y-3">
    <!-- Avatar -->
    <%= image_tag(client.avatar_thumb, 
        class: "object-cover w-24 h-24 sm:w-32 sm:h-32 mx-2 rounded-full border border-white", alt: "avatar")%>
    <!-- User name -->
    <%= tag.h4 client.user_name , class: "font-medium text-2xl text-center hover:underline text-gray-800" %>
    <!-- Total products -->
    <% if client.products.where(published: true).count.positive? && action_name != 'modal'%>
        <%= link_to user_products_path(client), 
            class: "flex items-center text-md font-medium hover:underline text-gray-500 mb-3", 
            data: { turbo_frame: '_top' }, target: "_blank" do
        %>
            <%= "#{t('product.total_products')}: #{client.products.where(published: true).count}" %>
            <%= heroicon 'cursor-arrow-rays', class: "ml-1 w-6 h-6 text-orange-700 hover:text-gray-800" %>
        <% end  %>
    <% elsif client.products.where(published: true).count.positive? %>
        <%= tag.span ("#{t('product.total_products')}: #{client.products.where(published: true).count}"), 
            class: "text-md font-medium hover:underline text-gray-500 mb-3" %>
    <% end %>
    
    <!-- Message -->
    <%= form_with model: Room.new, remote: true, data: {turbo_frame: user_signed_in? ? '_top' : 'modal'} do |f| %>
        <%= f.hidden_field :recipient_id, value: client.id%>
        <%= f.button class: "text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm py-2 px-4 text-center flex items-center" do %>
            <%= heroicon 'chat-bubble-left-right', class: 'w-6 h-6 mr-2'%>
            Написать
        <% end %>
    <% end %>
    
    <!-- Contacts -->
    <%= render 'users/users/contacts_section', user: client%>
    <!-- Created_at -->
    <!-- <div class="flex justify-center text-center">
        <%= tag.span client.decorate.created_at, class: 'text-sm text-gray-500'%>
    </div> -->
</section>

app/views/clients/shared/_client_menu.html.erb
<!-- Client menu links list -->
<hr>
<!-- Chats -->
<%= link_to rooms_path, 
  class: link_class, 
  data: {action: "dropdown#toggle"}, 
  tabindex:"-1",
  id:"profilePageLink" do
%>
 <%= heroicon "chat-bubble-left-right", class: "w-4 h-4 rtl:ml-2 ltr:mr-2" %>
 <%= t('user_menu.chats')%>
<% end %>

<hr>
<!-- New product -->
<%= link_to new_users_product_path, 
   class: link_class, 
   data: {action: "dropdown#toggle"}, 
   tabindex:"-1",
   id:"profilePageLink" do
%>
   <%= heroicon "plus-circle", class: "w-4 h-4 rtl:ml-2 ltr:mr-2" %>
   <%= t('product.add_btn')%>
<% end %>

<!-- All products -->
<%= link_to users_products_path, 
   class: link_class, 
   data: { action: "dropdown#toggle" }, 
   tabindex:"-1",
   id:"profilePageLink" do
%>
   <%= image_tag(asset_path('icons/icons8-lounge-50.png'), class: "w-4 h-4 rtl:ml-2 ltr:mr-2")%>
   <%= t('product.my_products')%>
<% end %>

<hr>

<!-- Saved list -->
<%= link_to users_favorites_path, 
   class: link_class, 
   data: { action: "dropdown#toggle" }, 
   tabindex:"-1",
   id:"profilePageLink" do
%>
   <%= heroicon "bookmark", class: "w-4 h-4 rtl:ml-2 ltr:mr-2" %>
   <%= t('user_menu.saved')%>
<% end %>

<hr>
<!-- Dashboard page -->
<!-- <%= link_to clients_dashboard_path,
  class: link_class,
  data: {action: "dropdown#toggle"},
  tabindex:"-1",
  id:"profilePageLink" do
%>
 <%= heroicon "rectangle-group", class: "w-4 h-4 rtl:ml-2 ltr:mr-2" %>
 <%= t('user_menu.dashboard')%>
<% end %> -->

<!-- Profile Info -->
<%= link_to edit_clients_profile_path, 
  class: link_class, 
  data: {action: "dropdown#toggle"}, 
  tabindex:"-1",
  id:"personalInfoLink" do
%>
  <%= heroicon "identification", class: "w-4 h-4 rtl:ml-2 ltr:mr-2" %>
  <%= t('user_menu.profile')%>
<% end %>

<!-- Credential Info -->
<%= link_to edit_client_registration_path, 
  class: link_class, 
  data: { action: "dropdown#toggle" }, 
  tabindex:"-1",
  id:"password&SecurityLink" do 
%>
  <%= heroicon "lock-closed", class: "w-4 h-4 rtl:ml-2 ltr:mr-2" %>
  <%= t('user_menu.credential')%>
<% end %>

<hr>
<!-- Sign Out -->
<%= link_to destroy_client_session_path, 
  class: link_class,
  data: {action: "dropdown#toggle", turbo_method: :delete, turbo_confirm: t('global.are_you_sure')},  
  tabindex:"-1", 
  id:"signOutLink" do 
%>
 <%= heroicon "arrow-right-on-rectangle", class: "w-4 h-4 rtl:ml-2 ltr:mr-2" %>
 <%= t('user_menu.sign_out')%>
<% end %>

app/views/clients/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>