config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    request.env['warden'].user(:admin).present?
  end
end

Rails.application.routes.default_url_options[:host] =
  Rails.env.production? ? 'http://chick-chuck.com' : 'localhost:3000'
Rails.application.routes.draw do
  # WWW redirect
  match '(*any)',
        to: redirect(subdomain: ''),
        via: :all,
        constraints: { subdomain: 'www' }
  # 404 old pages to remove!
  get '/he', to: redirect('/404')
  get '/he/*other', to: redirect('/404')
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    # 404
    get '404', to: 'errors#page_not_found'
    # 404 old pages to remove!
    # get "/contents/*other", to: redirect('/404')
    # get "/news/*other", to: redirect('/404')
    # get "/trucks/*other", to: redirect('/404')
    # Root path
    root to: 'main#index'
    # Sitemap
    get 'sitemap.xml', to: 'main#sitemap', format: 'xml', as: :sitemap
    # Robots
    get 'robots.txt',  to: 'main#robots',  format: 'txt', as: :robots
    # Favicon
    get 'favicon.png', to: 'main#favicon', format: 'png', as: :favicon
    # Cookies
    get 'cookies', to: 'main#cookies', as: :cookies, defaults: { format: 'turbo_stream' }

    # --- Content ---

    # Users
    resources :users, only: %i[index show], controller: 'users/users', path: 'carriers' do
      get '/modal',         to: 'users/users#modal',                  as: 'modal'
      get '/contacts',      to: 'users/users#contacts',               as: 'contacts'
    end

    # Products
    resources :products, only: %i[index show], controller: 'contents/products'
    get 'seller/:user_id', to: 'contents/products#user_products', as: 'user_products'

    # Calculator
    resource :calculator, only: %i[show], controller: 'contents/calculators' do
      get '/company/:company_id/calculator', to: 'contents/calculators#company_calculator', as: 'company'
    end

    # Moving preparation
    get '/moving_preparation', to: 'contents/moving_preparation#index', as: 'moving_preparation'

    # Comments
    resources :comments, only: %i[new edit create update destroy], controller: 'feedbacks/comments' do
      resources :comments, only: %i[new edit create update destroy], controller: 'feedbacks/comments'
    end

    # About service
    get 'about', to: 'contents/about#index', as: 'about'

    # Feedbacks
    resources :feedbacks, only: %i[index create edit update], controller: 'contents/feedbacks'

    # News content
    # resources :news, only: %i[show index], controller: 'contents/news' do
    #   resources :comments, only: %i[new edit create update destroy], controller: 'feedbacks/comments'
    # end

    # --- End of content ---

    # Admins
    devise_for :admins, controllers: { registrations: 'admins/registrations' }, skip: %i[registrations confirmations]
    as :admin do
      get 'admins/edit',  to: 'admins/registrations#edit',    as: 'edit_admin_registration'
      put 'admins',       to: 'admins/registrations#update',  as: 'admin_registration'
      namespace :admins, constraints: AdminConstraint.new do
        # Analytics
        mount ActiveAnalytics::Engine => '/analytics'
        # Sidekiq
        mount Sidekiq::Web => '/sidekiq'
        resources :categories, except: %i[show], controller: 'catalog/categories' do
          resources :things, except: %i[show], controller: 'catalog/things'
        end
        resources :news, except: %i[show]
        resources :languages, except: %i[index show]
        resources :districts, except: %i[show] do
          resources :cities
        end
        resource :dashboard, only: :show do
          get :users
        end
        post '/publish/news/:id', to: 'news#publish', as: 'publish_news'
      end
    end

    # Companies
    devise_for :companies, controllers: { registrations: 'companies/registrations' }
    namespace :companies do
      resources :prices,     only: %i[index create update]
      resource  :calculator, only: %i[create update]
      resource  :gallery,    only: %i[show create]
      get  '/dashboard',                to: 'dashboard#index',              as: 'dashboard'
      get  '/profile',                  to: 'profiles#profile',             as: 'edit_profile'
      put  '/profile',                  to: 'profiles#profile_update',      as: 'profile'
      get  '/company_info',             to: 'profiles#company_info',        as: 'edit_company_info'
      put  '/company_info',             to: 'profiles#company_info_update', as: 'company_info'
    end

    # Clients
    devise_for :clients, controllers: { registrations: 'clients/registrations' }, skip: :omniauth_callbacks
    namespace :clients do
      resource :profile, only: %i[edit update]
      get '/dashboard', to: 'dashboard#index', as: 'dashboard'
    end

    # Users
    namespace :users do
      resources :favorites, only: %i[index create destroy]
      resources :products, except: %i[show] do
        post '/publish',      to: 'products#publish',             as: 'publish'
        post '/mark_as_sold', to: 'products#mark_as_sold',        as: 'mark_as_sold'
      end
      # Email subscribers
      resources :mailers, only: [:create]
    end

    # Reviews
    resources :reviews, only: %i[new create edit update], controller: 'feedbacks/reviews'

    # Carrierwave attachments
    namespace :carrierwave do
      resources :images, only: %i[show destroy]
    end

    # Rooms
    resources :rooms, only: %i[index show create], param: :title, controller: 'feedbacks/rooms' do
      resources :messages, only: %i[edit update create destroy], controller: 'feedbacks/messages'
    end

    # Notifications
    resources :notifications, only: [:index], controller: 'feedbacks/notifications'
  end

  # Devise with omniauth_callbacks
  devise_for :clients, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'clients/omniauth_callbacks' }
end

app/helpers/navigation_helper.rb
# frozen_string_literal: true

module NavigationHelper
  def nav_tab(title, url, options = {})
    current_page = options.delete :current_page

    css_class = current_page == title ? '!text-gray-900' : 'text-gray-500'

    options[:class] = if options[:class]
                        "#{options[:class]} #{css_class}"
                      else
                        css_class
                      end

    link_to title, url, options
  end

  def currently_at(current_page = '')
    render partial: 'shared/navigations/header', locals: { current_page: }
    render partial: 'shared/navigations/footer', locals: { current_page: }
  end

  def full_title(page_title = '')
    base_title = 'Chick-Chuck'
    if page_title.present?
      "#{page_title} | #{base_title}"
    else
      base_title
    end
  end

  def current_locale_path(locale)
    url = request.original_url

    if url.include?('/sign_in')
      new_session_path(resource, locale:)
    elsif url.include?('/confirmation/new')
      new_confirmation_path(resource, locale:)
    elsif url.include?('/password/new')
      new_password_path(resource, locale:)
    else
      url_for(locale:)
    end
  end
end

app/views/shared/navigations/_companies_filter.html.erb
<!-- Trucks filter -->
<%= form_with url: path, method: :get, data: {turbo_frame: frame, controller: 'checkbox-select-all'} do |f| %>
    <% tag.div class: "w-full absolute #{[action_name, controller_name].eql?(['index', 'main']) ? 'bottom-0' : 'top-0'} inline-flex items-center z-10 grid grid-cols-1 sm:grid-cols-4 border-gray-700 bg-gray-700 border bg-opacity-90 rounded-tl-3xl rounded-br-3xl sm:mx-auto", data: { controller: "reveal" } do %>
        <!-- District -->
        <div class="w-full h-14 items-center flex bg-opacity-90 font-medium rtl:pr-3 ltr:pl-3 rounded-tl-3xl rtl:sm:rounded-none hidden sm:flex"
             data-reveal-target="item"
        >
            <%= heroicon 'map', class: 'w-6 h-6 mr-1 text-gray-400' %>
            <%= f.collection_select(:district_id, District.all.decorate, :id, :title, 
            { include_blank: District.model_name.human, selected: params[:district_id]}, 
            {class: "h-full text-base md:rounded-l-xl block w-full p-2.5 placeholder-gray-400 text-gray-300 hover:text-gray-100 focus:ring-0 focus:border-gray-100 focus:text-gray-100 border-0 rounded-tl-3xl rtl:bg-left rtl:ml-3 sm:ml-0 bg-opacity-90 #{controller_name == 'main' ? 'bg-gray-700/0' : 'bg-gray-600'}"})%>
        </div>
        <!-- Language -->
        <div class="w-full h-14 items-center flex relative bg-opacity-90 font-medium rtl:pr-3 rtl:rounded-tl-3xl ltr:pl-3 hidden sm:flex"
            data-reveal-target="item"
        >
            <%= heroicon 'language', class: 'w-6 h-6 mr-1 text-gray-400' %>
            <%= f.collection_select(:language_id, Language.all, :id, :title, {include_blank: Language.model_name.human, selected: params[:language_id]}, {class: "h-full text-base block w-full p-2.5  placeholder-gray-400 text-gray-300 hover:text-gray-100 focus:ring-0 focus:border-gray-100 focus:text-gray-100 border-0 rtl:rounded-tl-3xl rtl:bg-left rtl:ml-3 bg-opacity-90 #{controller_name == 'main' ? 'bg-gray-700/0' : 'bg-gray-600'}"})%>
        </div>
        <!-- Services -->
        <div class="w-full h-14 items-center flex justify-center border-0  relative bg-opacity-90 hidden sm:flex"
            data-reveal-target="item"
        >
            <!-- Button -->
            <button id="dropdownServicesButton" data-dropdown-toggle="dropdownServices" class="inline-flex items-center w-full text-base font-medium text-center text-gray-300 hover:text-gray-100" type="button">
                <%= heroicon 'list-bullet', class: 'w-6 h-6 mx-3 text-gray-400' %>
                <%= Company.human_attribute_name('services')%>
            </button>
            <!-- Services dropdown menu -->
            <div id="dropdownServices" class="z-10 hidden rounded-lg shadow bg-gray-700 min-w-full">
                <ul class="h-72 px-3 pb-3 overflow-y-auto rounded-lg bg-gray-700 min-w-full text-start" aria-labelledby="dropdownServicesButton">
                    <!-- Select All / Deselect All -->
                    <li class="flex items-center p-2 rounded-lg">
                        <label class="text-base form-control block w-full p-2 font-normal text-gray-300 hover:text-gray-100 bg-clip-padding rounded-lg border border-solid border-gray-500">
                            <input type="checkbox" data-checkbox-select-all-target="checkboxAll" />
                            <%= tag.span "#{t('global.select_all')} / #{t('global.deselect_all')}"%>
                        </label>
                    </li>
                    <!-- Services list -->
                    <%= f.collection_check_boxes(:service_ids, Service.all.decorate, :id, :title, multiple: true, checked: params[:service_ids]) do |b| %> 
                        <li class="flex items-center p-2 rounded-lg">
                            <%= b.label(class: "text-base form-control block w-full p-2 font-normal text-gray-300 hover:text-gray-100 bg-clip-padding rounded-lg border border-solid border-gray-500") do %>
                                <%= b.check_box data: { checkbox_select_all_target: 'checkbox' } %>
                                <%= b.text %>
                            <% end %>
                        </li>
                    <% end%>
                </ul>
            </div>
        </div>
        <!-- Search button -->
        <div class=" w-full h-auto p-3 flex justify-center items-center space-x-2 rtl:space-x-reverse">
            <button data-action="click->reveal#toggle" type="button" class="btn sm:hidden" title="filter-params">
                <%= heroicon 'adjustments-horizontal', class: 'w-7 h-7 text-gray-300'%>
            </button>
            
            <%= button_tag t('company.find_carrier'), class: "flex items-center justify-center w-full px-2 py-2 h-full text-base font-medium rounded-lg border bg-opacity-90 focus:ring-1 focus:outline-none focus:ring-gray-300 #{controller_name == 'main' ? 'bg-orange-700 border-orange-700 hover:bg-orange-800 text-gray-300' : 'bg-blue-600 border-blue-600 hover:bg-blue-700 text-gray-100'}", name: "find carrier" %>
        </div>
    <% end %>
<% end %>

app/views/shared/navigations/_content_links_list.html.erb
<!-- Content links list -->
<!-- Home -->
<%= nav_tab t('pages.home'), root_path, 
    class: link_class, current_page: current_page, 
    data: {action: "dropdown#toggle", turbo_frame: '_top'} %>
<!-- Carriers -->
<%= nav_tab t('company.carriers').capitalize, users_path,
    class: link_class, current_page: current_page, 
    data: {action: "dropdown#toggle", turbo_frame: '_top'} %>
<!-- Market -->
<%= nav_tab t('pages.market'), products_path,
    class: link_class, current_page: current_page, 
    data: {action: "dropdown#toggle", turbo_frame: '_top'} %>
<!-- Calculator -->
<%= nav_tab t('pages.calculator'), calculator_path,
    class: link_class, current_page: current_page, 
    data: {action: "dropdown#toggle", turbo_frame: '_top'} %>
<!-- About service -->
<div data-controller="dropdown" class="relative">
  <button type="button" data-action="dropdown#toggle click@window->dropdown#hide" 
      class="<%= link_class %> flex items-center text-gray-500 justify-center w-full">
      <%= t('pages.knowledge_base')%>
      <svg class="w-5 h-5 ml-1" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
  </button>

  <div
    data-dropdown-target="menu"
    class="hidden transition transform origin-top-right absolute right-0 z-10 border font-normal bg-gray-50 divide-y divide-gray-100 rounded-lg shadow w-full lg:w-[12rem]"
    data-transition-enter-from="opacity-0 scale-95"
    data-transition-enter-to="opacity-100 scale-100"
    data-transition-leave-from="opacity-100 scale-100"
    data-transition-leave-to="opacity-0 scale-95"
  >
      <ul class="py-2 text-sm text-gray-700 dark:text-gray-400 text-center divide-y divide-gray-200" aria-labelledby="dropdownAbout">
        <li>
          <!-- Moving preparation -->
          <%= nav_tab t('moving_preparation.title'), moving_preparation_path,
              class: "#{link_class} px-4 py-2 hover:bg-gray-100 block w-full !mx-0", current_page: current_page, 
              data: {action: "dropdown#toggle", turbo_frame: '_top'} %>
        </li>
        <li>
          <!-- About -->
          <%= nav_tab t('pages.about'), about_path,
              class: "#{link_class} px-4 py-2 hover:bg-gray-100 block w-full !mx-0", current_page: current_page, 
              data: {action: "dropdown#toggle", turbo_frame: '_top'} %>
        </li>
        <li>
            <!-- Feedbacks -->
            <%= nav_tab t('review.reviews'), feedbacks_path,
                class: "#{link_class} px-4 py-2 hover:bg-gray-100 block w-full !mx-0", current_page: current_page, 
                data: {action: "dropdown#toggle", turbo_frame: '_top'} %>
        </li>
      </ul>
  </div>
</div>
<!-- News -->
<% if News.count.positive? %>
    <%= nav_tab t('pages.news'), news_index_path,
        class: link_class, current_page: current_page, 
        data: {action: "dropdown#toggle", turbo_frame: '_top'} %>
<% end %>

app/views/shared/navigations/_mobile_menu.html.erb
<!-- Dropdown mobile menu -->
<div 
  id="mobile-menu-button"
  data-dropdown-target="menu"
  data-transition-enter-from="opacity-0 scale-95"
  data-transition-enter-to="opacity-100 scale-100"
  data-transition-leave-from="opacity-100 scale-100"
  data-transition-leave-to="opacity-0 scale-95"
  class="hidden absolute z-50 top-0 inset-x-0 p-2 transition transform origin-top-right lg:hidden overflow-y-auto max-h-screen"
>
    <div class="rounded-lg shadow-lg ring-1 ring-black ring-opacity-5 bg-white divide-y-2 divide-gray-50">
      <!-- Dropdown menu header -->
      <div class="pt-5 pb-6 px-5">
        <div class="flex items-center justify-between">
          <div>
            <%= link_to root_path, class: 'flex items-center' do %>
                <%= image_tag('logo/chick-chuck-logo.webp', class: "h-10 w-56 object-cover", alt: 'chick-chuck-logotype') %>
            <% end %>
          </div>
          <div class="-mr-2">
            <button 
                data-action="dropdown#toggle click@window->dropdown#hide" 
                type="button" class="bg-white rounded-lg p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500"
            >
                <%= heroicon 'x-mark', class: 'h-6 w-6'%>
            </button>
          </div>
        </div>
      </div>
      <!-- Main navigations -->
      <div class="py-6 px-5 space-y-6 text-center">
        <div class="grid grid-cols-1 gap-y-3 gap-x-8">
            <!-- Links list -->
            <%= render 'shared/navigations/content_links_list', 
                link_class: "text-base font-medium text-gray-500 hover:text-gray-900 pb-3 border-b border-gray-200",
                current_page: current_page %>
            <!-- Become a carrier -->
            <%= tag.div class: "flex justify-center" do %>
                <%= link_to new_company_registration_path, class: "relative inline-flex items-center justify-center p-0.5 overflow-hidden text-base font-medium rounded-lg group bg-gradient-to-br from-green-400 to-blue-600 group-hover:from-green-400 group-hover:to-blue-600 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-green-200 dark:focus:ring-green-800
                #{current_page?(new_company_registration_path) ? 'text-gray-900' : 'text-gray-600'}" do %>
                  <span class="relative px-4 py-1.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
                      <%= t('company.sign_up.link')%>
                  </span>
                <% end %>
            <% end unless user_signed_in?%>
        </div>
      </div>
    </div>
</div>

app/views/shared/navigations/_profile_navigation.html.erb
<div class="flex items-center py-5 overflow-y-auto whitespace-nowrap">
    <!-- Back -->
    <%= link_to (heroicon I18n.locale == :he ? "arrow-uturn-right" : "arrow-uturn-left", class: "w-5 h-5 hover:text-black"), :back %>
    <%= tag.span '/', class: "mx-5 text-gray-700"%>

    <!-- Home path -->
    <%= link_to (heroicon "home", class: "w-5 h-5 hover:text-black"), root_path %>    
    <%= tag.span '/', class: "mx-5 text-gray-700" if admin_signed_in? || company_signed_in?%>

    <!-- Dashboard path -->
    <%= link_to t('user_menu.dashboard'), admins_dashboard_path, class: "text-gray-700 hover:underline" if admin_signed_in?%>
    <%= link_to t('user_menu.dashboard'), companies_dashboard_path, data: {turbo:false},
        class: "text-gray-700 hover:underline" if company_signed_in?%>
    <%# link_to t('user_menu.dashboard'), clients_dashboard_path, class: "text-gray-700 hover:underline" if client_signed_in?%>

    <!-- Parent path -->
    <% if yield(:parent_title).present? && yield(:parent_path).present?%>
        <%= tag.span '/', class: "mx-5 text-gray-700"%>
        <%= link_to yield(:parent_title), yield(:parent_path), class: "text-gray-700 hover:underline" %>
    <% end %>
    
    <!-- Current path -->
    <%= tag.span '/', class: "mx-5 text-gray-700"%>
    <%= link_to yield(:nav_title), yield(:nav_path), class: "text-gray-700 hover:underline" %>
   
</div>

app/views/shared/navigations/_user_menu.html.erb
<% if user_signed_in? %>
    <!-- Message Notifications -->
    <%= render 'feedbacks/messages/notifications/notifications_section'%>
    <!-- Notifications -->
    <%= render 'feedbacks/notifications/notifications_section'%>
<% end %>

<div class="flex items-center space-x-4">
    <!-- Become a Carrier -->
    <%= link_to new_company_registration_path, class: "hidden relative xl:inline-flex items-center justify-center p-0.5 overflow-hidden text-base font-medium rounded-lg group bg-gradient-to-br from-green-400 to-blue-600 group-hover:from-green-400 group-hover:to-blue-600 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-green-200 dark:focus:ring-green-800
        #{current_page?(new_company_registration_path) ? 'text-gray-900' : 'text-gray-600'}" do %>
      <span class="relative px-4 py-1 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
          <%= t('company.sign_up.link')%>
      </span>
    <% end unless user_signed_in?%>
    <!-- User menu -->
    <div class="relative z-40" data-controller="dropdown">
        <!-- User menu button -->
        <div>
          <button 
            id="user-menu-button"
            aria-label="user-dropdown-menu"
            data-action="dropdown#toggle click@window->dropdown#hide"
            class="flex text-sm rounded-full border-2 border-gray-300 hover:border-gray-400 focus:outline-none drop-shadow-2xl hover:drop-shadow-lg items-center" 
          >
            <%= heroicon "bars-3", class: "mx-2 hidden sm:block", size: 20 %>
            <!-- Avatar -->
            <% if user_signed_in? %>
                <%= image_tag(current_user.avatar_thumb, 
                    class: "object-cover h-8 w-8 rounded-full border border-gray-500 m-1", alt: "user-avatar")%>
            <% else %>
                <%= heroicon "user-circle", class: "w-8 h-8 text-gray-600 rounded-full border m-1" %>
            <% end %>
          </button>
        </div>

        <!-- User menu dropdown -->
        <div 
            data-dropdown-target="menu"
            class="hidden absolute rtl:origin-top-left rtl:left-0 ltr:origin-top-right ltr:right-0 z-50 mt-2 min-w-[14rem] w-auto rounded-lg shadow-md hover:shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none" 
            data-transition-enter-from="opacity-0 scale-95"
            data-transition-enter-to="opacity-100 scale-100"
            data-transition-leave-from="opacity-100 scale-100"
            data-transition-leave-to="opacity-0 scale-95"
        >
            <% if user_signed_in? %>
                <!-- User menu header -->
                <%= tag.div class: "flex flex-col items-center my-3 mx-2", 
                  data: {action: "dropdown#toggle"}, 
                  tabindex:"-1",
                  id:"personalInfoLink" do
                %>
                    <!-- Avatar -->
                    <%= image_tag(current_user.avatar_thumb, class: "object-cover w-16 h-16 mx-2 mb-3 rounded-full", alt: "user-avatar")%>
                    <!-- User name -->
                    <%= tag.h4 (current_user.user_name), class: "px-4 font-medium text-gray-800 text-center hover:underline"%>
                    <!-- Email -->
                    <%= tag.p current_user.email, class: "px-4 py-2 text-sm font-medium text-gray-600 text-center hover:underline"%>
                <% end %>
                <!-- Links list -->
                <%= render 'clients/shared/client_menu', 
                    link_class: "font-medium flex block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 items-center" if client_signed_in?%>
                <%= render 'companies/shared/company_menu', 
                    link_class: "font-medium flex block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 items-center" if company_signed_in?%>
                <%= render 'admins/shared/admin_menu', 
                    link_class: "font-medium flex block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 items-center" if admin_signed_in?%> 
            <% else %>
                <!-- Sign In -->
                <%= link_to t('user_menu.sign_in'), new_client_session_path, 
                    class: "font-medium block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100", 
                    data: {action: "dropdown#toggle", turbo_frame: 'modal'}, 
                    tabindex:"-1",
                    id: "clientSignInLink"
                %>
                <!-- Sign Up -->
                <%= link_to t('user_menu.sign_up'), new_client_registration_path, 
                    class: "font-medium block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100", 
                    data: {action: "dropdown#toggle"}, 
                    tabindex:"-1",
                    id: "clientSignUpLink"
                %>
                <hr>
                <!-- Company -->
                <div class="m-2 min-w-[14rem] w-auto inline-flex items-center justify-center p-0.5 overflow-hidden text-base font-medium rounded-lg group bg-gradient-to-br from-green-400 to-blue-600 group-hover:from-green-400 group-hover:to-blue-600 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-green-200 dark:focus:ring-green-800">
                    <span class="w-full relative  py-1 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md">
                        <!-- Sign In As Company-->
                        <%= link_to new_company_session_path, 
                            class: "font-medium flex block  px-2 py-2 text-sm text-gray-700 hover:bg-gray-100 items-center", 
                            data: {action: "dropdown#toggle", turbo_frame: 'modal'}, 
                            tabindex:"-1",
                            id: "companySignInLink" do
                        %>
                            <%= image_tag(asset_path('icons/icons8-in-transit-50.png'), 
                                class: "w-4 h-4 rtl:ml-2 ltr:mr-2", alt: "log-in-as-company")%>
                            <%= t('user_menu.sign_in_company')%>
                        <% end %>
                        <!-- Become a Carrier -->
                        <%= link_to new_company_registration_path, 
                            class: "font-medium flex block  px-2 py-2 text-sm text-gray-700 hover:bg-gray-100 items-center", 
                            data: {action: "dropdown#toggle"}, 
                            tabindex:"-1",
                            id:"companySignUpLink" do
                        %>
                                <%= image_tag(asset_path('icons/icons8-in-transit-50.png'), 
                                    class: "w-4 h-4 rtl:ml-2 ltr:mr-2 flex-none", alt: "become-a-carrier")%>
                                <%= t('company.sign_up.title')%>
                        <% end %>
                    </span>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/shared/navigations/_user_profile_sidebar.html.erb
<div class="bg-white rounded py-3 px-4 shadow-md hidden lg:block min-h-screen h-full -mb-20 pb-14">
    <!-- User sidebar menu header -->
    <div class="flex flex-col items-center my-3 mx-2">
        <!-- Avatar -->
        <%= image_tag(current_user.avatar_thumb, class: "object-cover w-24 h-24 mx-2 mb-3 rounded-full", alt: "user-avatar")%>
        <!-- Name -->
        <%= tag.h4 current_user.user_name, class: "break-all mx-2 font-medium text-xl text-gray-800 text-center hover:underline" %>
        <!-- Email -->
        <%= tag.p current_user.email, class: "break-all mx-2 mt-1 text-base font-medium text-gray-600 text-center hover:underline"%>
    </div>
    
    <!-- User sidebar menu links list -->
    <ul class="space-y-1 text-sm my-3">
        <%= render 'admins/shared/admin_menu',
            link_class: "flex items-center text-base space-x-3 text-gray-700 p-2 rounded-md font-medium hover:bg-gray-100 focus:bg-gray-200 focus:shadow-outline" if admin_signed_in?%>
        <%= render 'clients/shared/client_menu', 
            link_class: "flex items-center text-base space-x-3 text-gray-700 p-2 rounded-md font-medium hover:bg-gray-100 focus:bg-gray-200 focus:shadow-outline" if client_signed_in?%>
        <%= render 'companies/shared/company_menu', 
            link_class: "flex items-center text-base space-x-3 text-gray-700 p-2 rounded-md font-medium hover:bg-gray-100 focus:bg-gray-200 focus:shadow-outline" if company_signed_in?%>
    </ul>
</div>