config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    request.env['warden'].user(:admin).present?
  end
end

Rails.application.routes.default_url_options[:host] =
  Rails.env.production? ? 'http://chick-chuck.com' : 'localhost:3000'
Rails.application.routes.draw do
  # WWW redirect
  match '(*any)',
        to: redirect(subdomain: ''),
        via: :all,
        constraints: { subdomain: 'www' }
  # 404 old pages to remove!
  get '/he', to: redirect('/404')
  get '/he/*other', to: redirect('/404')
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    # 404
    get '404', to: 'errors#page_not_found'
    # 404 old pages to remove!
    # get "/contents/*other", to: redirect('/404')
    # get "/news/*other", to: redirect('/404')
    # get "/trucks/*other", to: redirect('/404')
    # Root path
    root to: 'main#index'
    # Sitemap
    get 'sitemap.xml', to: 'main#sitemap', format: 'xml', as: :sitemap
    # Robots
    get 'robots.txt',  to: 'main#robots',  format: 'txt', as: :robots
    # Favicon
    get 'favicon.png', to: 'main#favicon', format: 'png', as: :favicon
    # Cookies
    get 'cookies', to: 'main#cookies', as: :cookies, defaults: { format: 'turbo_stream' }

    # --- Content ---

    # Users
    resources :users, only: %i[index show], controller: 'users/users', path: 'carriers' do
      get '/modal',         to: 'users/users#modal',                  as: 'modal'
      get '/contacts',      to: 'users/users#contacts',               as: 'contacts'
    end

    # Products
    resources :products, only: %i[index show], controller: 'contents/products'
    get 'seller/:user_id', to: 'contents/products#user_products', as: 'user_products'

    # Calculator
    resource :calculator, only: %i[show], controller: 'contents/calculators' do
      get '/company/:company_id/calculator', to: 'contents/calculators#company_calculator', as: 'company'
    end

    # Moving preparation
    get '/moving_preparation', to: 'contents/moving_preparation#index', as: 'moving_preparation'

    # Comments
    resources :comments, only: %i[new edit create update destroy], controller: 'feedbacks/comments' do
      resources :comments, only: %i[new edit create update destroy], controller: 'feedbacks/comments'
    end

    # About service
    get 'about', to: 'contents/about#index', as: 'about'

    # Feedbacks
    resources :feedbacks, only: %i[index create edit update], controller: 'contents/feedbacks'

    # News content
    # resources :news, only: %i[show index], controller: 'contents/news' do
    #   resources :comments, only: %i[new edit create update destroy], controller: 'feedbacks/comments'
    # end

    # --- End of content ---

    # Admins
    devise_for :admins, controllers: { registrations: 'admins/registrations' }, skip: %i[registrations confirmations]
    as :admin do
      get 'admins/edit',  to: 'admins/registrations#edit',    as: 'edit_admin_registration'
      put 'admins',       to: 'admins/registrations#update',  as: 'admin_registration'
      namespace :admins, constraints: AdminConstraint.new do
        # Analytics
        mount ActiveAnalytics::Engine => '/analytics'
        # Sidekiq
        mount Sidekiq::Web => '/sidekiq'
        resources :categories, except: %i[show], controller: 'catalog/categories' do
          resources :things, except: %i[show], controller: 'catalog/things'
        end
        resources :news, except: %i[show]
        resources :languages, except: %i[index show]
        resources :districts, except: %i[show] do
          resources :cities
        end
        resource :dashboard, only: :show do
          get :users
        end
        post '/publish/news/:id', to: 'news#publish', as: 'publish_news'
      end
    end

    # Companies
    devise_for :companies, controllers: { registrations: 'companies/registrations' }
    namespace :companies do
      resources :prices,     only: %i[index create update]
      resource  :calculator, only: %i[create update]
      resource  :gallery,    only: %i[show create]
      get  '/dashboard',                to: 'dashboard#index',              as: 'dashboard'
      get  '/profile',                  to: 'profiles#profile',             as: 'edit_profile'
      put  '/profile',                  to: 'profiles#profile_update',      as: 'profile'
      get  '/company_info',             to: 'profiles#company_info',        as: 'edit_company_info'
      put  '/company_info',             to: 'profiles#company_info_update', as: 'company_info'
    end

    # Clients
    devise_for :clients, controllers: { registrations: 'clients/registrations' }, skip: :omniauth_callbacks
    namespace :clients do
      resource :profile, only: %i[edit update]
      get '/dashboard', to: 'dashboard#index', as: 'dashboard'
    end

    # Users
    namespace :users do
      resources :favorites, only: %i[index create destroy]
      resources :products, except: %i[show] do
        post '/publish',      to: 'products#publish',             as: 'publish'
        post '/mark_as_sold', to: 'products#mark_as_sold',        as: 'mark_as_sold'
      end
      # Email subscribers
      resources :mailers, only: [:create]
    end

    # Reviews
    resources :reviews, only: %i[new create edit update], controller: 'feedbacks/reviews'

    # Carrierwave attachments
    namespace :carrierwave do
      resources :images, only: %i[show destroy]
    end

    # Rooms
    resources :rooms, only: %i[index show create], param: :title, controller: 'feedbacks/rooms' do
      resources :messages, only: %i[edit update create destroy], controller: 'feedbacks/messages'
    end

    # Notifications
    resources :notifications, only: [:index], controller: 'feedbacks/notifications'
  end

  # Devise with omniauth_callbacks
  devise_for :clients, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'clients/omniauth_callbacks' }
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  validates :ru, :en, :he, presence: true, uniqueness: true
  has_many :things, dependent: :destroy
  has_many :products
end

app/controllers/admins/catalog/categories_controller.rb
# frozen_string_literal: true

module Admins
  module Catalog
    class CategoriesController < ApplicationController
      layout 'profile_layout'
      before_action :authenticate_admin!
      before_action :set_category, only: %i[edit update destroy]

      def new
        @category = Category.new
      end

      def create
        @category = Category.new(category_params).decorate
        respond_to do |format|
          if @category.save
            format.turbo_stream do
              flash.now[:success] =
                t('flash.success.created', model: "#{@category.model_name.human} #{@category.title.downcase}")
            end
          else
            format.html { render :new, status: :unprocessable_entity }
          end
        end
      end

      def index
        @categories = Category.all.decorate
      end

      def edit; end

      def update
        respond_to do |format|
          if @category.update(category_params)
            format.turbo_stream do
              flash.now[:success] =
                t('flash.success.updated', model: "#{@category.model_name.human} #{@category.title.downcase}")
            end
          else
            format.html { render :new, status: :unprocessable_entity }
          end
        end
      end

      def destroy
        respond_to do |format|
          if @category.destroy
            format.turbo_stream do
              flash.now[:success] = t('flash.success.destroyed', model: @category.model_name.human)
            end
          else
            format.html { render :new, status: :unprocessable_entity }
          end
        end
      end

      private

      def category_params
        params.require(:category).permit(:ru, :en, :he, :uk)
      end

      def set_category
        @category = Category.find_by_id(params[:id]).decorate
      end
    end
  end
end

app/controllers/admins/catalog/things_controller.rb
# frozen_string_literal: true

module Admins
  module Catalog
    class ThingsController < ApplicationController
      layout 'profile_layout'
      before_action :authenticate_admin!
      before_action :set_thing, only: %i[edit update destroy]
      before_action :set_category

      def new
        @thing = @category.things.new
      end

      def create
        @thing = @category.things.build(thing_params).decorate
        respond_to do |format|
          if @thing.save
            format.turbo_stream do
              flash.now[:success] =
                t('flash.success.created', model: "#{@thing.model_name.human} #{@thing.title.downcase}")
            end
          else
            format.html { render :new, target: helpers.dom_id(@category, 'thing_form'), status: :unprocessable_entity }
          end
        end
      end

      def index
        @things = @category.things.decorate
      end

      def edit; end

      def update
        respond_to do |format|
          if @thing.update(thing_params)
            format.turbo_stream do
              flash.now[:success] =
                t('flash.success.updated', model: "#{@thing.model_name.human} #{@thing.title.downcase}")
            end
          else
            format.html { render :edit, status: :unprocessable_entity }
          end
        end
      end

      def destroy
        respond_to do |format|
          if @thing.destroy
            format.turbo_stream { flash.now[:success] = t('flash.success.destroyed', model: @thing.model_name.human) }
          else
            format.html { render :new, status: :unprocessable_entity }
          end
        end
      end

      private

      def thing_params
        params.require(:thing).permit(:ru, :en, :he, :uk)
      end

      def set_category
        @category = Category.find_by_id(params[:category_id])
      end

      def set_thing
        @thing = Thing.find_by_id(params[:id]).decorate
      end
    end
  end
end

app/views/admins/catalog/categories/_category.html.erb
<%= turbo_frame_tag category do %>
    <!-- Category title -->
    <%= turbo_frame_tag dom_id(category, 'form'), 
        class: 'items-center flex mx-auto my-4 w-full relative border-b border-b-gray-300 hover:border-b-gray-500' do %>
        <%= tag.p category.ru, class: "text-start text-gray-500 text-xl font-bold uppercase" %>
        <p class="mx-2">|</p>
        <%= tag.p category.en, class: "text-start text-gray-500 text-xl font-bold uppercase" %>
        <p class="mx-2">|</p>
        <%= tag.p category.uk, class: "text-start text-gray-500 text-xl font-bold uppercase" %>
        <p class="mx-2">|</p>
        <%= tag.p category.he, class: "text-start text-gray-500 text-xl font-bold uppercase" %>
        <%= link_to edit_admins_category_path(category), data: {turbo_frame: dom_id(category, 'form')},
            class: 'absolute right-0 flex py-0 mr-2 text-base font-medium justify-end items-center text-end text-gray-500 hover:text-gray-700 hover:underline' do %>
            <%= heroicon 'pencil-square', class: 'w-5 h-5 text-gray-900'%>
        <% end %>
    <% end %>
    <!-- Things -->
    <%= tag.div id:dom_id(category, 'things'), class: "overflow-x-auto mb-4" do %>
        <div class="grid grid-cols-9 gap-6 bg-gray-200 p-1">
            <%= tag.div 'Ru', class: 'col-span-2'%>
            <%= tag.div 'En', class: 'col-span-2'%>
            <%= tag.div 'Uk', class: 'col-span-2'%>
            <%= tag.div 'He', class: 'col-span-2'%>
        </div>
        <%= render partial: 'admins/catalog/things/thing', collection: category.things%>
    <% end %>
    <!-- Add thing -->
    <%= render 'shared/buttons/add', id: dom_id(category, "thing_form"), title: t('thing.add_btn'), path: new_admins_category_thing_path(category)%>
<% end %>

app/views/admins/catalog/categories/_form.html.erb
<!-- Calculator categories form -->
<%= turbo_frame_tag dom_id(@category, 'form') do %>
    <%= form_with model: [:admins, @category], class: "col-span-full mx-auto my-4 w-full relative" do |f| %>
        <!-- Error messages -->
        <%= tag.div (render 'shared/error_messages', resource: @category), class: 'col-span-full' %>
        <div class="w-full items-center flex grid grid-cols-1 md:grid-cols-4 gap-3">
          <!-- Ru -->
          <div class="flex items-center text-gray-600 justify-center">
              <div class="flex items-center text-center">
                  <%= f.label :ru, 'Ru', class: "text-lg mr-2" %>
              </div>
              <%= f.text_field :ru, class: "w-full mr-1 text-gray-700 bg-white border border-gray-300 rounded-md  focus:border-blue-500 dark:focus:border-blue-500 focus:outline-none focus:ring"%>
          </div>
          <!-- En -->
          <div class="flex items-center text-gray-600 justify-center">
              <div class="flex items-center text-center">
                  <%= f.label :en, 'En', class: "text-lg mr-2" %>
              </div>
              <%= f.text_field :en, class: "w-full mr-1 text-gray-700 bg-white border border-gray-300 rounded-md  focus:border-blue-500 dark:focus:border-blue-500 focus:outline-none focus:ring"%>
          </div>
          <!-- Uk -->
          <div class="flex items-center text-gray-600 justify-center">
              <div class="flex items-center text-center">
                  <%= f.label :uk, 'Uk', class: "text-lg mr-2" %>
              </div>
              <%= f.text_field :uk, class: "w-full mr-1 text-gray-700 bg-white border border-gray-300 rounded-md  focus:border-blue-500 dark:focus:border-blue-500 focus:outline-none focus:ring"%>
          </div>
          <!-- He -->
          <div class="flex items-center text-gray-600 justify-center">
              <div class="flex items-center text-center">
                  <%= f.label :he, 'He', class: "text-lg mr-2" %>
              </div>
              <%= f.text_field :he, class: "w-full mr-1 text-gray-700 bg-white border border-gray-300 rounded-md  focus:border-blue-500 dark:focus:border-blue-500 focus:outline-none focus:ring"%>
          </div>
        </div>
        <div class="flex items-center justify-start mt-4">
          <!-- Button Save -->
          <div class="flex justify-start pb-2">
              <%= f.submit t('global.save_btn'), class: "cursor-pointer px-6 py-2 leading-5 text-white transition-colors duration-200 transform  rounded-md  focus:outline-none bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4"%>
          </div>
          <!-- Button delete -->
          <div class="flex justify-start pb-2 ml-3">
              <%= link_to t('global.destroy_btn'), admins_category_path(@category), data: {turbo_method: :delete, turbo_confirm: t('global.are_you_sure')},
                  class: "cursor-pointer px-6 py-2 leading-5 text-white transition-colors duration-200 transform  rounded-md  focus:outline-none bg-gradient-to-r from-red-500 via-red-600 to-red-700 hover:bg-gradient-to-br focus:ring-4" if action_name == 'edit'%>
          </div>
        </div>
    <% end %>
<% end %>

app/views/admins/catalog/categories/create.turbo_stream.erb
<%= turbo_stream.replace dom_id(Category.new, 'form') do %>
    <%= render 'shared/buttons/add', id: dom_id(Category.new, 'form'), title: t('admin.add_category'), path: new_admins_category_path%>
<% end %>

<%= turbo_stream.append 'categories', render(@category)%>
<%= prepend_flash%>

app/views/admins/catalog/categories/destroy.turbo_stream.erb
<%= turbo_stream.remove @category%>
<%= prepend_flash%>

app/views/admins/catalog/categories/edit.html.erb
<% currently_at t('admin.edit_category') %>
<% provide :page_title, t('admin.edit_category') %>
<% provide :nav_title, t('admin.edit_category') %>
<% provide :nav_path, '#' %>
<% provide :main_title, t('admin.edit_category') %>

<%= render 'form', path: admins_category_path, method: :put%>

app/views/admins/catalog/categories/index.html.erb
<% currently_at t('admin_menu.catalog') %>
<% provide :page_title, t('admin_menu.catalog') %>
<% provide :nav_title, t('admin_menu.catalog') %>
<% provide :nav_path, admins_categories_path %>
<% provide :main_title, t('admin_menu.catalog') %>

<!-- Categories table -->
<%= turbo_frame_tag 'categories',
    class: "grid grid-flow-row auto-rows-max w-full overflow-x-auto" do 
%>
    <%= render @categories %>
<% end %>

<!-- New category -->
<hr class="my-6">
<%= render 'shared/buttons/add', id: dom_id(Category.new, 'form'), title: t('category.add_btn'), path: new_admins_category_path%>

app/views/admins/catalog/categories/new.html.erb
<% currently_at 'New category' %>
<% provide :page_title, 'New category' %>
<% provide :nav_title, 'New category' %>
<% provide :nav_path, '#' %>
<% provide :main_title, "New category" %>

<%= render 'form', path: admins_categories_path, method: :post%>

app/views/admins/catalog/categories/update.turbo_stream.erb
<%= turbo_stream.replace dom_id(@category, 'form') do %>
    <%= turbo_frame_tag dom_id(@category, 'form'), class: 'items-center flex mx-auto my-4 w-full relative border-b border-b-gray-300' do %>
        <%= tag.p @category.ru, class: "text-start text-gray-500 text-xl font-bold uppercase" %>
        <p class="mx-2">|</p>
        <%= tag.p @category.en, class: "text-start text-gray-500 text-xl font-bold uppercase" %>
        <p class="mx-2">|</p>
        <%= tag.p @category.he, class: "text-start text-gray-500 text-xl font-bold uppercase" %>
        <%= link_to edit_admins_category_path(@category), data: {turbo_frame: dom_id(@category, 'form')},
            class: 'absolute right-0 flex py-0 mr-2 text-base font-medium justify-end items-center text-end text-gray-500 hover:text-gray-700 hover:underline' do %>
            <%= image_tag(asset_path('icons/icons8-edit-48.png'), class: 'w-5 h-5')%>
        <% end %>
    <% end %>
<% end %>

<%= prepend_flash%>