config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    request.env['warden'].user(:admin).present?
  end
end

Rails.application.routes.default_url_options[:host] =
  Rails.env.production? ? 'http://chick-chuck.com' : 'localhost:3000'
Rails.application.routes.draw do
  # WWW redirect
  match '(*any)',
        to: redirect(subdomain: ''),
        via: :all,
        constraints: { subdomain: 'www' }
  # 404 old pages to remove!
  get '/he', to: redirect('/404')
  get '/he/*other', to: redirect('/404')
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    # 404
    get '404', to: 'errors#page_not_found'
    # 404 old pages to remove!
    # get "/contents/*other", to: redirect('/404')
    # get "/news/*other", to: redirect('/404')
    # get "/trucks/*other", to: redirect('/404')
    # Root path
    root to: 'main#index'
    # Sitemap
    get 'sitemap.xml', to: 'main#sitemap', format: 'xml', as: :sitemap
    # Robots
    get 'robots.txt',  to: 'main#robots',  format: 'txt', as: :robots
    # Favicon
    get 'favicon.png', to: 'main#favicon', format: 'png', as: :favicon
    # Cookies
    get 'cookies', to: 'main#cookies', as: :cookies, defaults: { format: 'turbo_stream' }

    # --- Content ---

    # Users
    resources :users, only: %i[index show], controller: 'users/users', path: 'carriers' do
      get '/modal',         to: 'users/users#modal',                  as: 'modal'
      get '/contacts',      to: 'users/users#contacts',               as: 'contacts'
    end

    # Products
    resources :products, only: %i[index show], controller: 'contents/products'
    get 'seller/:user_id', to: 'contents/products#user_products', as: 'user_products'

    # Calculator
    resource :calculator, only: %i[show], controller: 'contents/calculators' do
      get '/company/:company_id/calculator', to: 'contents/calculators#company_calculator', as: 'company'
    end

    # Moving preparation
    get '/moving_preparation', to: 'contents/moving_preparation#index', as: 'moving_preparation'

    # Comments
    resources :comments, only: %i[new edit create update destroy], controller: 'feedbacks/comments' do
      resources :comments, only: %i[new edit create update destroy], controller: 'feedbacks/comments'
    end

    # About service
    get 'about', to: 'contents/about#index', as: 'about'

    # Feedbacks
    resources :feedbacks, only: %i[index create edit update], controller: 'contents/feedbacks'

    # News content
    # resources :news, only: %i[show index], controller: 'contents/news' do
    #   resources :comments, only: %i[new edit create update destroy], controller: 'feedbacks/comments'
    # end

    # --- End of content ---

    # Admins
    devise_for :admins, controllers: { registrations: 'admins/registrations' }, skip: %i[registrations confirmations]
    as :admin do
      get 'admins/edit',  to: 'admins/registrations#edit',    as: 'edit_admin_registration'
      put 'admins',       to: 'admins/registrations#update',  as: 'admin_registration'
      namespace :admins, constraints: AdminConstraint.new do
        # Analytics
        mount ActiveAnalytics::Engine => '/analytics'
        # Sidekiq
        mount Sidekiq::Web => '/sidekiq'
        resources :categories, except: %i[show], controller: 'catalog/categories' do
          resources :things, except: %i[show], controller: 'catalog/things'
        end
        resources :news, except: %i[show]
        resources :languages, except: %i[index show]
        resources :districts, except: %i[show] do
          resources :cities
        end
        resource :dashboard, only: :show do
          get :users
        end
        post '/publish/news/:id', to: 'news#publish', as: 'publish_news'
      end
    end

    # Companies
    devise_for :companies, controllers: { registrations: 'companies/registrations' }
    namespace :companies do
      resources :prices,     only: %i[index create update]
      resource  :calculator, only: %i[create update]
      resource  :gallery,    only: %i[show create]
      get  '/dashboard',                to: 'dashboard#index',              as: 'dashboard'
      get  '/profile',                  to: 'profiles#profile',             as: 'edit_profile'
      put  '/profile',                  to: 'profiles#profile_update',      as: 'profile'
      get  '/company_info',             to: 'profiles#company_info',        as: 'edit_company_info'
      put  '/company_info',             to: 'profiles#company_info_update', as: 'company_info'
    end

    # Clients
    devise_for :clients, controllers: { registrations: 'clients/registrations' }, skip: :omniauth_callbacks
    namespace :clients do
      resource :profile, only: %i[edit update]
      get '/dashboard', to: 'dashboard#index', as: 'dashboard'
    end

    # Users
    namespace :users do
      resources :favorites, only: %i[index create destroy]
      resources :products, except: %i[show] do
        post '/publish',      to: 'products#publish',             as: 'publish'
        post '/mark_as_sold', to: 'products#mark_as_sold',        as: 'mark_as_sold'
      end
      # Email subscribers
      resources :mailers, only: [:create]
    end

    # Reviews
    resources :reviews, only: %i[new create edit update], controller: 'feedbacks/reviews'

    # Carrierwave attachments
    namespace :carrierwave do
      resources :images, only: %i[show destroy]
    end

    # Rooms
    resources :rooms, only: %i[index show create], param: :title, controller: 'feedbacks/rooms' do
      resources :messages, only: %i[edit update create destroy], controller: 'feedbacks/messages'
    end

    # Notifications
    resources :notifications, only: [:index], controller: 'feedbacks/notifications'
  end

  # Devise with omniauth_callbacks
  devise_for :clients, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'clients/omniauth_callbacks' }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include Login
  include FormattedPhone
  include Notificable
  include Filterable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable,
         :validatable, authentication_keys: [:login]

  mount_uploader :avatar, AvatarUploader

  validates :first_name, :last_name, allow_blank: true, length: { in: 2..25 }
  has_one :feedback, class_name: 'Feedback', dependent: :destroy
  has_and_belongs_to_many :rooms, class_name: 'Room', dependent: :destroy
  has_many :comments, class_name: 'Comment', dependent: :destroy
  has_many :messages, class_name: 'Message', dependent: :destroy
  has_many :reviews, class_name: 'Review', dependent: :destroy

  has_many :favorites, foreign_key: :user_id, dependent: :destroy

  # Scopes
  scope :filter_by_type, ->(type) { where type: }
  scope :filter_by_user_name, lambda { |user_name|
                                User.all.select do |user|
                                  user.user_name.downcase.include?(user_name.downcase)
                                end
                              }
end

app/controllers/users/favorites_controller.rb
# frozen_string_literal: true

module Users
  class FavoritesController < ApplicationController
    layout 'profile_layout'
    before_action :authenticate_user!

    def index
      @favorite_items = current_user.favorites
      @favorite_items_count = @favorite_items.count
      @pagy, @favorite_items = pagy(@favorite_items, items: 10)
    end

    def create
      @favorite = current_user.favorites.build(favorite_params)

      respond_to do |format|
        if @favorite.save
          format.turbo_stream do
            flash.now[:success] = t('flash.success.saved', model: @favorite.favorited.title)
          end
        else
          format.html { redirect :back, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @favorite = Favorite.find(params[:id])
      @object = @favorite.favorited

      respond_to do |format|
        if @favorite.destroy
          format.turbo_stream { flash.now[:success] = t('flash.success.destroyed', model: @favorite.favorited.title) }
        else
          format.html { redirect :back, status: :unprocessable_entity }
        end
      end
    end

    private

    def favorite_params
      params.require(:favorite).permit(:favorited_id, :favorited_type)
    end
  end
end

app/controllers/users/mailers_controller.rb
# frozen_string_literal: true

module Users
  class MailersController < ApplicationController
    def create
      subscriber = Subscriber.new(subscriber_params)

      respond_to do |format|
        if Subscriber.find_by(email: subscriber_params[:email]).present? || User.where(email: subscriber_params[:email]).present?
          format.turbo_stream { flash.now[:alert] = t('flash.mailers.info') }
        elsif subscriber.save
          format.turbo_stream { flash.now[:success] = t('flash.mailers.success') }
        end
      end
    end

    private

    def subscriber_params
      params.require(:subscriber).permit(:email)
    end
  end
end

app/controllers/users/products_controller.rb
# frozen_string_literal: true

module Users
  class ProductsController < ApplicationController
    include Feedbacks::ReviewsHelper
    layout 'profile_layout'
    before_action :authenticate_user!, except: :new
    before_action :set_product, only: %i[edit update publish mark_as_sold destroy]
    before_action :filter_product, only: %i[new create edit update]

    def index
      @pagy, @products = pagy(current_user.products.newest, items: 8, fragment: '#products')
      @products = @products.decorate
    end

    def new
      unless client_signed_in? || company_signed_in?
        return redirect_to new_client_session_path,
                           alert: t('devise.failure.unauthenticated')
      end

      @product = current_user.products.new.decorate
    end

    def create
      @product = current_user.products.build(product_params).decorate

      respond_to do |format|
        if @product.save
          helpers.upload_image(@product)
          format.turbo_stream do
            flash.now[:success] = t('flash.success.created', model: "#{@product.model_name.human} #{@product.title}")
          end
        else
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    def edit; end

    def update
      respond_to do |format|
        if @product.update(product_params)
          helpers.upload_image(@product)
          format.turbo_stream do
            flash.now[:success] = t('flash.success.updated', model: "#{@product.model_name.human} #{@product.title}")
          end
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    def publish
      return unless current_user.products.include?(@product)

      respond_to do |format|
        if @product.published == false
          if @product.update(published: true)
            format.turbo_stream do
              flash.now[:success] =
                t('flash.success.published', model: "#{@product.model_name.human} #{@product.title}")
            end
          end
        elsif @product.update(published: false)
          format.turbo_stream do
            flash.now[:success] = t('flash.success.hided', model: "#{@product.model_name.human} #{@product.title}")
          end
        end
      end
    end

    def mark_as_sold
      return unless current_user.products.include?(@product)

      respond_to do |format|
        if @product.sold == false
          @product.update(sold: true, published: false)
          format.turbo_stream do
            flash.now[:success] = t('flash.success.hided', model: "#{@product.model_name.human} #{@product.title}")
          end
        else
          @product.update(sold: false, published: true)
          format.turbo_stream do
            flash.now[:success] =
              t('flash.success.published', model: "#{@product.model_name.human} #{@product.title}")
          end
        end
      end
    end

    def destroy
      respond_to do |format|
        if @product.destroy
          format.turbo_stream { flash.now[:success] = t('flash.success.destroyed', model: @product.model_name.human) }
        else
          format.html { render :index, status: :unprocessable_entity }
        end
      end
    end

    private

    def product_params
      params.require(:product).permit(:category_id, :thing_id, :district_id, :city_id, :title, :condition, :delivery,
                                      :description, :price, { images_attributes: %i[id file] })
    end

    def filter_product
      @categories = Category.where.not(en: 'Cartons').decorate
      @districts = District.where.not(en: 'All Israel').decorate
    end

    def set_product
      @product = Product.find_by_id(params[:product_id] || params[:id]).decorate
    end
  end
end

app/controllers/users/users_controller.rb
# frozen_string_literal: true

module Users
  class UsersController < ApplicationController
    include Feedbacks::ReviewsHelper
    include PricesHelper
    before_action :set_user, only: %i[show modal contacts]
    after_action  :update_views, only: :show

    def index
      set_meta_tags(
        title: t('meta.carriers.title'),
        description: t('meta.carriers.desc'),
        keywords: Service.all.decorate.map(&:title).join(', ').sub(/(, )+$/, ''),
        noindex: request.original_url.include?('?') ? true : false,
        alternate: {
          'x-default' => users_url(locale: nil),
          'en' => users_url(locale: :en),
          'ru' => users_url(locale: :ru),
          'uk' => users_url(locale: :uk)
        }
      )

      companies = Company.confirmed.user_filter(filter_params)
      @best_companies = companies.take(3)
      latest_companies = companies.drop(3)
      @companies_count = latest_companies.count
      @pagy_a, @latest_companies = pagy_array(latest_companies, items: 8)
    end

    def show
      set_meta_tags(
        title: [t('israel'), @user.user_name.capitalize],
        keywords: @user.services.decorate.map(&:title).join(', ').sub(/(, )+$/, ''),
        description: @user.instance_of?(Company) && @user.description.present? ? @user.description.to_s : "#{@user.user_name.capitalize} | #{t('company.carriers').capitalize} | #{t('home_page.main_features.reviews_desc')}",
        og: {
          image: @user.avatar.url
        }
      )

      return redirect_to root_path unless @user.instance_of?(Company)

      @commentable = @user
      @comment = Comment.new
      @reviewable = @user
      @review = current_client&.company_review(@reviewable) || Review.new
      @reviews = @user.reviews.where.not(content: nil || '', title: nil || '')
      @reviews_count = @reviews.count
      @pagy, @reviews = pagy(@reviews, items: 10, fragment: '#reviews')
    end

    def modal
      set_meta_tags(
        title: [t('user_menu.profile'), @user.user_name.capitalize],
        description: "#{@user.user_name.capitalize} | #{t('user_menu.profile')}",
        noindex: true
      )
    end

    def contacts
      set_meta_tags(
        title: [t('contacts'), @user.user_name.capitalize],
        description: "#{@user.user_name.capitalize} | #{t('contacts')} | #{t('contacts_desc_html')}"
      )
      # return redirect_to new_client_session_path, alert: t('devise.failure.unauthenticated') unless user_signed_in?
    end

    private

    def filter_params
      params.permit(:district_id, :language_id, { service_ids: [] })
    end

    def set_user
      @user = User.find(params[:user_id] || params[:id])
    end

    def update_views
      return if request.is_crawler? || current_admin || current_company == @user

      @user.update(views: @user.views + 1)
    end
  end
end

app/views/users/form/_contacts_section.html.erb
<!-- Contact Information -->
<hr>
<h6 class="text-gray-500 text-xl my-6 font-bold uppercase">
  <%= t('contacts')%>
</h6>

<div class="grid grid-cols-1 gap-6 md:grid-cols-2 mb-6">
    <!-- Additional Phone input -->
    <div class="">
       <%= form.label :additional_phone, class: "text-lg" %>
       <%= form.text_field :additional_phone, 
        class: "text-base form-control block w-full px-4 py-2 mt-1 font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none",
        placeholder: User.human_attribute_name('additional_phone'), value: current_user.formatted_additional_phone,
        required: false
       %>
    </div>

    <!-- WhatsApp input -->
    <div class="">
       <%= form.label :whatsapp, 'WhatsApp', class: "text-lg" %>
       <%= form.text_field :whatsapp, 
        class: "text-base form-control block w-full px-4 py-2 mt-1 font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none",
        placeholder: '+(___) __-___ ____', value: current_user.formatted_whatsapp,
        required: false
       %>
    </div>

    <!-- Telegram input -->
    <div class="">
       <div class="flex items-center space-x-2 rtl:space-x-reverse">
           <%= form.label :telegram, 'Telegram', class: "text-lg" %>
           <!-- Popover button-->
           <%= render 'shared/buttons/popover', text: t('telegram.telegram_popover'), icon: 'icons/icons8-info-50.png'%>
       </div>
       <%= form.text_field :telegram, 
        class: "text-base form-control block w-full px-4 py-2 mt-1 font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none",
        placeholder: '@example', value: current_user.telegram,
        required: false
       %>
    </div>

    <!-- Facebook input -->
    <div class="">
       <div class="flex items-center space-x-2 rtl:space-x-reverse">
           <%= form.label :facebook, 'Facebook', class: "text-lg" %>
           <!-- Popover button-->
           <%= render 'shared/buttons/popover', text: t('facebook.facebook_popover'), icon: 'icons/icons8-info-50.png'%>
       </div>
       <%= form.text_field :facebook, 
        class: "text-base form-control block w-full px-4 py-2 mt-1 font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none",
        placeholder: 'https://web.facebook.com/example',
        required: false
       %>
    </div>
</div>

app/views/users/form/_credential_info_fields.html.erb
  <!-- Email input -->
  <div class="">
     <div class="flex items-center">
         <%= tag.span '*', class: "text-red-500 mr-1" if current_page?(new_registration_path(resource_name))%>
         <%= form.label :email, class: "text-lg" %>
     </div>
     <%= form.email_field :email, autofocus: true, autocomplete: "email", 
      class: "text-base form-control block w-full px-4 py-2 mt-1 font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none",
      id: "email-input",
      placeholder: "Email address",
      required: true
     %>
  </div>
  
  <!-- Phone input -->
  <div class="">
     <div class="flex items-center">
         <%= tag.span '*', class: "text-red-500 mr-1" if current_page?(new_registration_path(resource_name))%>
         <%= form.label :phone, class: "text-lg" %>
     </div>
     <%= form.text_field :phone, autocomplete: "phone", 
      class: "text-base form-control block w-full px-4 py-2 mt-1 font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none",
      id: "phone-input",
      placeholder: '+(972) __-___ ____',
      required: true
     %>
  </div>

  <!-- Password input -->
  <div class="">
    <div class="flex items-center">
        <%= tag.span '*', class: "text-red-500 mr-1" if current_page?(new_registration_path(resource_name))%>
        <%= form.label :password, class: "text-lg mr-1" %>
        <% if @minimum_password_length %>
            <!-- Popover button-->
            <%= render 'shared/buttons/popover', text: User.human_attribute_name('password_popover', length: @minimum_password_length)%>
        <% end %>
    </div>
    <%= form.password_field :password, autocomplete: "new-password",
      class: "text-base form-control block w-full px-4 py-2 mt-1 font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none",
      id: "password-input",
      placeholder: User.human_attribute_name('password'),
      required: true
    %>
  </div>

  <!-- Password confirmation -->
  <div class="">
     <div class="flex items-center">
         <%= tag.span '*', class: "text-red-500 mr-1" if current_page?(new_registration_path(resource_name))%>
         <%= form.label :password_confirmation, class: "text-lg" %>
     </div>
     <%= form.password_field :password_confirmation, autocomplete: "new-password",
       class: "text-base form-control block w-full px-4 py-2 mt-1 font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none",
       id: "passwordConfirmation-input",
       placeholder: User.human_attribute_name('password_confirmation'),
       required: true
     %>
  </div>

app/views/users/form/_form_edit_credentials.html.erb
<!-- Password & Security form -->
<%= form_for(resource, as: resource_name, url: registration_path(resource_name), 
    html: { method: :put }, data: { turbo: 'false'}) do |form| %>
  <%= render "shared/error_messages", resource: resource %>

    <div class="grid grid-cols-1 gap-6 mt-4">
        <!-- Credential info -->
        <%= render 'users/form/credential_info_fields', form: form %>
  
        <!-- Current password -->
        <%= tag.div class:"" do %>
         <div class="flex items-center">
             <span class="text-red-500 mr-1">&nbsp;*</span>
             <%= form.label :current_password, class: "text-lg mr-1" %>
             <!-- Popover button-->
             <%= render 'shared/buttons/popover', text: "#{User.human_attribute_name('current_popover')}"%>
         </div>
         <%= form.password_field :current_password, autocomplete: "current_password",
           class: "text-base form-control block w-full px-4 py-2 mt-1 font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none",
           id: "currentPassword-input",
           placeholder: User.human_attribute_name('current_password'),
           required: true
         %>
         <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
           <%= link_to t('sign_in.forgot'), new_password_path(resource_name), class: "text-gray-800" %>
         <% end %>
        <% end unless current_client && resource.provider.present?%>

        <!-- Buttons -->
        <div class="flex grid grid-cols-4">
          <!-- Button Save -->
          <div class="flex justify-start col-span-3">
              <%= form.submit t('global.save_btn'), class: "cursor-pointer px-6 py-2 leading-5 text-white transition-colors duration-200 transform  rounded-md  focus:outline-none bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4"%>
          </div>
        </div>  
    </div>
<% end %>     
 
  <!-- Delete account -->
  <div class="flex justify-end col-span-1 -mt-7">
      <%= link_to registration_path(resource_name), data: { turbo_method: :delete, turbo_confirm: t('sure_to_del_account') }, class: "justify-end items-center flex mx-0 leading-5 text-gray-700 " do %>
          <%= image_tag(asset_path('icons/icons8-remove-32.png'), class: 'w-5 h-5 mr-2')%>
           <%= User.human_attribute_name('delete_account')%>
      <% end %>
  </div>
  

app/views/users/form/_personal_info_fields.html.erb
<!-- First Name input -->
<div class="">
   <div class="flex items-center">
       <%= tag.span '*', class: "text-red-500 mr-1" if controller_name == 'registrations'%>
       <%= form.label :first_name, class: "text-lg" %>
   </div>
   <%= form.text_field :first_name, autocomplete: "first_name", 
    class: "text-base form-control block w-full px-4 py-2 mt-1 font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none",
    id: "firstName-input",
    placeholder: "#{User.human_attribute_name('first_name')}",
    required: true
   %>
</div>

<!-- Last Name input -->
<div class="">
   <div class="flex items-center">
       <%= tag.span '*', class: "text-red-500 mr-1" if controller_name == 'registrations'%>
       <%= form.label :last_name, class: "text-lg" %>
   </div>
   <%= form.text_field :last_name, autofocus: false, autocomplete: "last_name", 
    class: "text-base form-control block w-full px-4 py-2 mt-1 font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none",
    id: "lastName-input",
    placeholder: "#{User.human_attribute_name('last_name')}",
    required: true
   %>
</div>

<!-- City -->
<div class="">
    <div class="flex items-center">
        <%= tag.span '*', class: "text-red-500 mr-1" if controller_name == 'registrations'%>
        <%= form.label :city, class: "text-lg" %>
    </div>
    <%= form.grouped_collection_select(:city_id, District.all.decorate.drop(1), :cities, :title, :id, I18n.locale, 
        { include_blank: t('global.select'), selected: params[:city_id] || current_user&.city_id}, 
        {class: "block w-full px-4 py-2 mt-1 text-gray-500 bg-white border border-gray-300 rounded-md focus:border-blue-500 dark:focus:border-blue-500 focus:outline-none focus:ring"})%>
</div>

<!-- Gender -->
<%= tag.div class: "" do %>
   <div class="flex items-center">
       <%= tag.span '*', class: "text-red-500 mr-1" if controller_name == 'registrations'%>
       <%= form.label :gender, class: "text-lg" %>
   </div>
   <%= form.select(:gender, options_for_select([[User.human_attribute_name('male'), 'male'], [User.human_attribute_name('female'), 'female']], current_user&.gender), {include_blank: t('global.select')},
       {class: "text-base form-control block w-full px-4 py-2 mt-1 font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none", required: true})%>
<% end if current_client || current_page?(new_client_registration_path)%>

<!-- Birthday -->
<div class="">
   <%= form.label :birthday, class: "text-lg" %>
   <%= form.date_field :birthday, autocomplete: "birthday", 
    class: "text-base form-control block w-full px-4 py-2 mt-1 font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none",
    id: "birthday-input",
    placeholder: "#{User.human_attribute_name('birthday')}",
    required: true
   %>
</div>